### ISSUE TITLE
Set up Parse locally

### ISSUE THREAD

**Issue by elai-zz** [harsh29/planfit#3]
Provide step by step instructions on how to set up Parse locally for team members.

**Comment by elai-zz** [comment]
You should have gotten an invite to contribute to the heroku team app: https://dashboard.heroku.com/apps/planfit-codepath If you want to use another email than the one I used for you, just let me know and I will invite your new email. Our Heroku App is here: https://planfit-codepath.herokuapp.com/
1. Make a heroku account so you can access that page.
2. Get the repository from heroku (see instructions https://dashboard.heroku.com/apps/planfit-codepath/deploy/heroku-git)
3. Note, if you see that there's a warning saying you've cloned into an empty repository, follow this SO answer: http://stackoverflow.com/questions/35389389/how-can-i-host-my-own-parse-server-on-heroku-using-mongodb
4. Basically you'll have to zip the parse-server-example repo and dump it in your local heroku app repo and change the `index.js` file to match the Config Vars in the Heroku App
5. Note, the parse-server-example is what we are using https://github.com/ParsePlatform/parse-server-example, not the OS Parse Server repo! (I didn't realize this until just now...)
6. You can find the Config Vars under the Heroku App Page > Settings > Reveal Config Vars
7. You can try pushing to master, which will trigger a deploy, and nothing should change here: https://planfit-codepath.herokuapp.com/
8. To run locally, install `node`, `mongodb-runner start` then `npm install` to get all the npm modules.
9. `$ parse-server --appId planfit --masterKey <master key> --databaseURI mongodb://localhost/test`
10. You should be able to access serverURL: `http://localhost:1337/parse`, even though it says it's permission denied. 
11. Try running `curl -X POST -H "X-Parse-Application-Id: planfit" -H "X-Parse-Master-Key: <master key>" \
    -H "Content-Type: application/json" \
    -d '{"score":1337,"playerName":"Sean Plott","cheatMode":false}' \
    http://localhost:1337/parse/classes/GameScore
    You should get something like this back {"objectId":"6fR1Cribam","createdAt":"2016-11-12T18:16:01.200Z"`

**Comment by elai-zz** [comment]
I'm going to leave this ticket as open and assign it to you guys. Just comment here if you have questions or if you're successful, I'll close the ticket once you both have set it up.

**Comment by elai-zz** [comment]
You can also use https://dashboard.heroku.com/apps/planfit-codepath/resources to see what's in the MongoDB in prod (I'll call the Heroku environment prod for convenience). You can also locally  install Parse Dashboard and RoboMongo as written here: https://guides.codepath.com/ios/Configuring-a-Parse-Server#parse-dashboard

**Comment by harsh29** [comment]
@elai i was able to go through the entire setup instructions, that being said, i am not familiar with pricing model of using mongoDB on heroku, should we/should we not use the mongo url u have entered into index.js file?
thanks,
👍 
Harsh

**Comment by elai-zz** [comment]
Feel free to use the mongo url that is hooked up to our Heroku. I realized it's not the mLab that's charging me, it's the Heroku dynos we're using (so essentially Heroku).

**Comment by elai-zz** [comment]
Ok update time - tl;dr is on the Slack channel as pinned posts. I moved the Parse Server off of the team account and onto my personal account because we can't use free app as a team. I've added a team account on mLab so we can still browse what's on the MongoDB if necessary. 

I asked Heroku about the Free dynos type and they said that you have to use at least Hobby as a team. I moved it to my personal account so I can use the free dynos type. I think what you've done locally is fine and you can continue to use it for local development (just change the server string to `localhost:1337` in the API client code). However, note that https://planfit-codepath.herokuapp.com/ is no longer in use. I didn't delete the app on our team Heroku, I just shut it off so they won't charge my credit card 💳 . I've updated the existing PR to use our new app: https://planfit-parse-app.herokuapp.com/

The app ID is still "planfit", the master key did change but if you're running locally you should just reference your local `index.js`. I don't think we'll need it for prod.

Sorry for the confusion, and thanks for your understanding.

**Comment by elai-zz** [comment]
Marking this as done
