### ISSUE TITLE
Make a video by Thur, so on WED!

### ISSUE THREAD

**Issue by olyasorokina** [harsh29/planfit#44]
Minnie, might you be up for that challenge? You're good at talking :)) I can make a preliminary gif.

**Comment by elai-zz** [comment]
We should probably make better mocks 😛

**Comment by olyasorokina** [comment]
mock routines? I updated the today's one with images :)

**Comment by olyasorokina** [comment]
certainly need something better than exercise 0, 1, 2 in the hardcoded routines...yeah
